### ISSUE TITLE
Error when starting minecraft.

### ISSUE THREAD

**Issue by ZeroNyte** [Argent-Matter/gcys#40]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.19.2-1.2.3.a

### Recipe Viewer Installed

JEI

### Environment

starting the game.

### Cross-Mod Interaction

Unsure

### Other Installed Mods

AE2-Things-1.1.1.jar
AEAdditions-1.19.2-4.0.5.jar
AEInfinityBooster-1.19.2-1.2.0+11.jar
alexsmobs-1.21.1.jar
appleskin-forge-mc1.19-2.4.2.jar
Applied-Mekanistics-1.3.5.jar
appliedenergistics2-forge-12.9.9.jar
Aquaculture-1.19.2-2.4.17.jar
aquaculture_delight_1.0.0_forge_1.19.2.jar
architectury-6.6.92-forge.jar
AutoRegLib-1.8.2-55.jar
balm-forge-1.19.2-4.6.0.jar
baubley-heart-canisters-1.19.2-2.1.0.jar
betterstats-2.2.2+1.19.2.jar
biomemusic-1.19.2-2.2.jar
BiomesOPlenty-1.19.2-17.1.1.162.jar
Bookshelf-Forge-1.19.2-16.3.20.jar
chipped-forge-1.19.2-2.1.5.jar
chisels-and-bits-forge-1.3.146.jar
chisel_chipped_integration_v1.0.1_1.19.2.jar
citadel-2.1.4-1.19.jar
Clumps-forge-1.19.2-9.0.0+14.jar
cofh_core-1.19.2-10.3.1.48.jar
constructionwand-1.19.2-2.10.jar
Controlling-forge-1.19.2-10.0+7.jar
CorgiLib-forge-1.19.2-1.0.0.34.jar
CraftTweaker-forge-1.19.2-10.1.55.jar
CTM-1.19.2-1.1.6+8.jar
Cucumber-1.19.2-6.0.10.jar
cupboard-1.19.2-2.6.jar
curios-forge-1.19.2-5.1.6.3.jar
densemekanism-1.19.2-1.0.0.jar
DistantHorizons-2.1.2-a-1.19.2-forge-fabric.jar
dttectonic-1.1.10.jar
DynamicTrees-1.19.2-1.2.1.jar
DynamicTrees-Terralith-1.19.2-1.1.1.jar
DynamicTreesBOP-1.19.2-3.1.5.jar
DynamicTreesBYG-1.19.2-1.2.0.jar
DynamicTreesPlus-1.19.2-1.1.4.jar
DynamicTreesQuark-1.19.2-2.4.0.jar
embeddium-0.3.18+mc1.19.2.jar
FarmersDelight-1.19.2-1.2.4.jar
farmingforblockheads-forge-1.19.2-11.3.5.jar
ferritecore-5.0.3-forge.jar
FramedBlocks-6.8.6.jar
ftb-library-forge-1902.4.1-build.236.jar
ftb-ultimine-forge-1902.4.1-build.90.jar
gcyr-forge-1.19.2-0.1.1.b.jar
geckolib-forge-1.19-3.1.40.jar
gtceu-1.19.2-1.2.3.a.jar
Iceberg-1.19.2-forge-1.1.4.jar
ImmersiveEngineering-1.19.2-9.2.4-170.jar
immersive_paintings-0.6.7+1.19.2-forge.jar
immersive_weathering-1.19.2-1.2.10-forge.jar
industrial-foregoing-1.19.2-3.3.2.4-9.jar
Jade-1.19.1-forge-8.9.2.jar
javd-forge-4.0.1-build.2+mc1.19.2.jar
 jei-1.19.2-forge-11.6.0.1019.jar
jeimultiblocks-1.19.2-0.0.3.jar
JeiTweaker-forge-1.19.2-4.0.13.jar
journeymap-1.19.2-5.9.8-forge.jar
JustEnoughMekanismMultiblocks-1.19.2-3.4.jar
JustEnoughResources-1.19.2-1.2.3.243.jar
kotlinforforge-3.12.0-all.jar
LegendaryTooltips-1.19.2-forge-1.4.0.jar
macawsbridgesbop-1.19.2-1.5.jar
macawsbridgesbyg-1.19.2-1.4.jar
macawsroofsbop-1.19.2-1.4.jar
macawsroofsbyg-1.19.2-1.3.jar
mcw-bridges-3.0.1-mc1.19.2forge.jar
mcw-doors-1.1.1forge-mc1.19.2.jar
mcw-fences-1.1.2-mc1.19.2forge.jar
mcw-furniture-3.2.2-mc1.19.2forge.jar
mcw-lights-1.1.0-mc1.19.2forge.jar
mcw-roofs-2.3.0-mc1.19.2forge.jar
mcw-trapdoors-1.1.3-mc1.19.2forge.jar
mcw-windows-2.2.1-mc1.19.2forge.jar
mcwfencesbop-1.19.2-1.1.jar
mcwfencesbyg-forge-1.19.2-1.1.jar
mcwfurnituresbyg-1.19.2-1.2.jar
Mekanism-1.19.2-10.3.9.13.jar
MekanismAdditions-1.19.2-10.3.9.13.jar
MekanismGenerators-1.19.2-10.3.9.13.jar
MekanismTools-1.19.2-10.3.9.13.jar
mekanismtweaks-1.1.jar
modernfix-forge-5.18.0+mc1.19.2.jar
moonlight-1.19.2-2.3.6-forge.jar
MoreMekanismProcessing-1.19.2-3.0.jar
MouseTweaks-forge-mc1.19-2.23.jar
MysticalAgradditions-1.19.2-6.0.5.jar
MysticalAgriculture-1.19.2-6.0.14.jar
NaturesCompass-1.19.2-1.10.0-forge.jar
oculus-mc1.19.2-1.6.9.jar
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.6.jar
Patchouli-1.19.2-77.jar
Prism-1.19.1-1.0.2.jar
ProjectE-1.19.2-PE1.1.0.jar
Quark-3.4-418.jar
QuarkOddities-1.18.jar
quark_delight_1.0.0_forge_1.19.2.jar
resourcefullib-forge-1.19.2-1.1.24.jar
sophisticatedbackpacks-1.19.2-3.20.2.1035.jar
sophisticatedcore-1.19.2-0.6.4.605.jar
sound-physics-remastered-forge-1.19.2-1.4.5.jar
StorageDrawers-1.19-11.1.2.jar
tectonic-forge-1.19-2.3.5a.jar
TerraBlender-forge-1.19.2-2.0.1.136.jar
Terralith_1.19.3_v2.3.12.jar
thermalendergy-1.19.2-3.0.2-all.jar
thermal_cultivation-1.19.2-10.3.0.19.jar
thermal_dynamics-1.19.2-10.3.0.20.jar
thermal_expansion-1.19.2-10.3.1.25.jar
thermal_foundation-1.19.2-10.3.1.57.jar
thermal_innovation-1.19.2-10.3.0.20.jar
thermal_integration-1.19.2-10.3.0.19.jar
titanium-1.19.2-3.7.4-31.jar
waystones-forge-1.19.2-11.4.2.jar
YungsApi-1.19.2-Forge-3.8.10.jar
YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
YungsBetterEndIsland-1.19.2-Forge-1.0.jar
YungsBetterJungleTemples-1.19.2-Forge-1.0.1.jar
YungsBetterMineshafts-1.19.2-Forge-3.2.1.jar
YungsBetterNetherFortresses-1.19.2-Forge-1.0.6.jar
YungsBetterOceanMonuments-1.19.2-Forge-2.1.1.jar
YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar
YungsExtras-1.19.2-Forge-3.1.0.jar

### Expected Behavior

what I'd expect? well, it to just work as it should. Just start without hickups

### Actual Behavior

error on startup:
![image](https://github.com/user-attachments/assets/fc526f24-507e-45f1-86dd-9706d6b9fb26)

-- Head --
Thread: Render thread
Suspected Mod: 
	GregTech (gtceu), Version: 1.2.3.a
		at TRANSFORMER/gtceu@1.2.3.a/com.gregtechceu.gtceu.api.registry.GTRegistry.register(GTRegistry.java:86)
Stacktrace:
	at com.gregtechceu.gtceu.api.registry.GTRegistry.register(GTRegistry.java:86) ~[gtceu-1.19.2-1.2.3.a.jar%23328!/:?] {re:classloading}
-- MOD gcyr --
Details:
	Mod File: /D:/Minecraft/Instances/CYBER-NK0/mods/gcyr-forge-1.19.2-0.1.1.b.jar
	Failure message: Gregicality Rocketry (gcyr) has failed to load correctly
		java.lang.IllegalStateException: [register] registry gtceu:recipe_condition has been frozen
	Mod Version: 0.1.1.b
	Mod Issue URL: https://github.com/argent-matter/gcyr/issues
	Exception message: java.lang.IllegalStateException: [register] registry gtceu:recipe_condition has been frozen
Stacktrace:
	at com.gregtechceu.gtceu.api.registry.GTRegistry.register(GTRegistry.java:86) ~[gtceu-1.19.2-1.2.3.a.jar%23328!/:?] {re:classloading}
	at argent_matter.gcyr.common.data.GCyRRecipeConditions.init(GCyRRecipeConditions.java:10) ~[gcyr-forge-1.19.2-0.1.1.b.jar%23326!/:?] {re:classloading}
	at argent_matter.gcyr.GCyR.init(GCyR.java:33) ~[gcyr-forge-1.19.2-0.1.1.b.jar%23326!/:?] {re:classloading}
	at argent_matter.gcyr.forge.GCyRForge.<init>(GCyRForge.java:18) ~[gcyr-forge-1.19.2-0.1.1.b.jar%23326!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.2-43.4.2.jar%23409!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.2-43.4.2.jar%23408!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

### Steps to Reproduce

install mods, launch game.

**Comment by jmoiron** [comment]
Have you tried to run this with a more recent version of GTCEU?

```GregTech (gtceu), Version: 1.2.3.a```

This is quite old, the latest release is [1.3.1](https://www.curseforge.com/minecraft/mc-mods/gregtechceu-modern/files/5493708)

**Comment by ZeroNyte** [comment]
1.3.1 is for 1.21, not for 1.19.2, atleast, what curseforge says.

but atm playing a 1.20.1 pack that works with both.

**Comment by jmoiron** [comment]
Sorry I linked the wrong version, here is [1.3.1 for 1.20.1](https://www.curseforge.com/minecraft/mc-mods/gregtechceu-modern/files/5493660)

**Comment by screret** [comment]
1.19.2 is unsupported.
