### ISSUE TITLE
1.20.1-0.1.3-aa-fabric    java.lang.NullPointerException: Cannot invoke "com.gregtechceu.gtceu.api.machine.MachineDefinition.asStack()" because "com.gregtechceu.gtceu.common.data.GTMachines.HULL[10]" is null

### ISSUE THREAD

**Issue by Rofle44-git** [Argent-Matter/gcys#44]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.0.20.b

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

- Fabric API 0.92.2+1.20.1
- GregTech 1.0.20.b
- Gregicality Rocketry 0.1.3-aa

### Expected Behavior

Once I clicked on Singleplayer, which lead to Minecraft automatically generating a world since I have not created one yet on this instance, It crashed.

### Actual Behavior

It should have brought me to the "Create new World" menu

### Steps to Reproduce

1. Launch Minecraft
2. Click on Singleplayer (without any pre-existing saves)

### Additional Information

Crash Report:

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-08-23 20:55:41
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "com.gregtechceu.gtceu.api.machine.MachineDefinition.asStack()" because "com.gregtechceu.gtceu.common.data.GTMachines.HULL[10]" is null
	at argent_matter.gcyr.data.recipe.MiscRecipes.init(MiscRecipes.java:93)
	at argent_matter.gcyr.common.data.GCyRRecipes.init(GCyRRecipes.java:15)
	at argent_matter.gcyr.GCyRGTAddon.addRecipes(GCyRGTAddon.java:107)
	at com.gregtechceu.gtceu.common.data.GTRecipes.lambda$recipeAddition$0(GTRecipes.java:73)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.gregtechceu.gtceu.common.data.GTRecipes.recipeAddition(GTRecipes.java:73)
	at com.gregtechceu.gtceu.core.MixinHelpers.addDynamicDataPack(MixinHelpers.java:92)
	at net.minecraft.class_7237$class_7238.modify$bjo001$gtceu$injectDynamicData(class_7237.java:517)
	at net.minecraft.class_7237$class_7238.method_42099(class_7237.java:104)
	at net.minecraft.class_7237.method_42098(class_7237.java:29)
	at net.minecraft.class_525.method_31130(class_525.java:333)
	at net.minecraft.class_528.method_43462(class_528.java:169)
	at net.minecraft.class_528.<init>(class_528.java:95)
	at net.minecraft.class_526.method_25426(class_526.java:54)
	at net.minecraft.class_437.method_25423(class_437.java:297)
	at net.minecraft.class_310.method_1507(class_310.java:1080)
	at net.minecraft.class_442.method_19861(class_442.java:159)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:56)
	at net.minecraft.class_339.method_25402(class_339.java:189)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:299)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at argent_matter.gcyr.data.recipe.MiscRecipes.init(MiscRecipes.java:93)
	at argent_matter.gcyr.common.data.GCyRRecipes.init(GCyRRecipes.java:15)
	at argent_matter.gcyr.GCyRGTAddon.addRecipes(GCyRGTAddon.java:107)
	at com.gregtechceu.gtceu.common.data.GTRecipes.lambda$recipeAddition$0(GTRecipes.java:73)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.gregtechceu.gtceu.common.data.GTRecipes.recipeAddition(GTRecipes.java:73)
	at com.gregtechceu.gtceu.core.MixinHelpers.addDynamicDataPack(MixinHelpers.java:92)
	at net.minecraft.class_7237$class_7238.modify$bjo001$gtceu$injectDynamicData(class_7237.java:517)
	at net.minecraft.class_7237$class_7238.method_42099(class_7237.java:104)
	at net.minecraft.class_7237.method_42098(class_7237.java:29)
	at net.minecraft.class_525.method_31130(class_525.java:333)
	at net.minecraft.class_528.method_43462(class_528.java:169)
	at net.minecraft.class_528.<init>(class_528.java:95)
	at net.minecraft.class_526.method_25426(class_526.java:54)
	at net.minecraft.class_437.method_25423(class_437.java:297)
	at net.minecraft.class_310.method_1507(class_310.java:1080)
	at net.minecraft.class_442.method_19861(class_442.java:159)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:56)
	at net.minecraft.class_339.method_25402(class_339.java:189)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:299)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_442
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, gtceu:dynamic_assets
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2413)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.10.6-zen1-1-zen
	Java Version: 17.0.12, Arch Linux
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Arch Linux
	Memory: 1028527616 bytes (980 MiB) / 2139095040 bytes (2040 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5500
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: GA104 [GeForce RTX 3060 Ti Lite Hash Rate]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 8224.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 87680.92
	Virtual memory used (MB): 6317.54
	Swap memory total (MB): 79786.99
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	Fabric Mods: 
		ae2: Applied Energistics 2 15.2.12
			team_reborn_energy: Energy 3.0.0
		ae2mtfix: AE2 + Mouse Tweaks Fix 2.0.0+1.20.1+fabric
		architectury: Architectury 9.2.14
		balm-fabric: Balm 7.3.9
			kuma_api: KumaAPI 20.1.8
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		controlling: Controlling For Fabric 12.0.2
		craftingtweaks: Crafting Tweaks 18.2.5
		ears: Ears 1.4.6
		embeddium: Embeddium 0.3.25+mc1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			indium: Indium 1.99.99
			sodium: Sodium 0.5.11
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.16.2
			mixinextras: MixinExtras 0.4.1
		ftbbackups2: FTB Backups 2 1.0.23
		ftbessentials: FTB Essentials 2001.2.2
		ftblibrary: FTB Library 2001.2.4
		ftbteams: FTB Teams 2001.3.0
		gcyr: Gregicality Rocketry 0.1.3-aa
		gtceu: GregTech 1.0.20.b
			configuration: Configuration 2.2.0
			ldlib: LowDragLib 1.0.22.a
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				com_google_code_findbugs_jsr305: jsr305 3.0.2
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
					porting_lib_utility: Porting Lib Utility 2.1.1090+1.20
				porting_lib_tags: Porting Lib Tags 3.0
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
		iceberg: Iceberg 1.1.18
		jade: Jade 11.10.0+fabric
		jadeaddons: Jade Addons 5.3.1+fabric
		java: OpenJDK 64-Bit Server VM 17
		konkrete: Konkrete 1.8.1
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		leashmod: Leashable Players 1.0.6
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.19.1+mc1.20.1
		modmenu: Mod Menu 7.2.2
		mousetweaks: Mouse Tweaks 2.26
		nightautoconfig: Night Auto Config 1.0.6
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_hocon: hocon 3.8.0
			com_electronwill_night-config_json: json 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
			com_electronwill_night-config_yaml: yaml 3.8.0
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		pehkui: Pehkui 3.8.3+1.14.4-1.21
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		polylib: PolyLib 2000.0.3-build.143
		reframed: ReFramed 1.6.6
		rei_custom_command: REI Custom Command 2.2.0
		reicollapsibleentries: REI Collapsible Entries 3.1.1
		roughlyenoughitems: Roughly Enough Items 12.1.750
			error_notifier: Error Notifier 1.0.9
		searchables: Searchables 1.0.3
		shimmer: Shimmer 1.20.1-0.2.3
		shimmer-support-layer: Shimmer Support Layer 0.9.4-dev
		skinlayers3d: 3d-Skin-Layers 1.6.7
		sophisticatedbackpacks: Sophisticated Backpacks 3.19.5+mc1.20.1-SNAPSHOT-build.104
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			forgeconfigapiport: Forge Config API Port 8.0.0
			porting_lib_extensions: Porting Lib Extensions 2.3.0+1.20.1
				porting_lib_accessors: Porting Lib Accessors 2.3.0+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.0+1.20.1
				porting_lib_common: Porting Lib Common 2.3.0+1.20.1
				porting_lib_core: Porting Lib Core 2.3.0+1.20.1
				reach-entity-attributes: Reach Entity Attributes 2.4.0
			porting_lib_loot: Porting Lib Loot 2.3.0+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.0+1.20.1
			porting_lib_model_loader: Porting Lib Model Loader 2.3.0+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.0+1.20.1
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.0+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.0+1.20.1
		sophisticatedcore: Sophisticated Core 0.5.109+mc1.20.1-SNAPSHOT-build.104
			porting_lib_fluids: Porting Lib Fluids 2.3.0+1.20.1
		sophisticatedstorage: Sophisticated Storage 0.8.60+mc1.20.1-SNAPSHOT-build.104
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.4.5
		trashslot: TrashSlot 15.1.0
		vcinteraction: Voice Chat Interaction 1.20.1-1.0.6
			polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.0+1.20
		visuality: Visuality 0.7.1+1.20
		voicechat: Simple Voice Chat 1.20.1-2.5.20
		xaeroworldmap: Xaero's World Map 1.38.8
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yosbr: YOSBR 0.1.2
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 555.58.02, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 12x AMD Ryzen 5 5500
```

**Comment by screret** [comment]
fabric is unsupported.
