### ISSUE TITLE
Crash for 2nd player on dedicated server on rocket launch.

### ISSUE THREAD

**Issue by Pyriana** [Argent-Matter/gcys#56]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gcyr-1.20.1-0.2.4

### Recipe Viewer Installed

EMI

### Environment

Dedicated Server

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Quantum Skies

### Expected Behavior

No crash for player watching the rocket launch, or riding in 2nd seat.

### Actual Behavior

Crash for player watching the launch or riding in 2nd seat.

### Steps to Reproduce

Wait for player on rocket to press launch button and crash immediately. Only happens if you're in the same dimension as the rocket launching

### Additional Information

Has happened in 2 separate chunks.

**Comment by screret** [comment]
crash log, please?

**Comment by Pyriana** [comment]
> crash log, please?

I believe this is it, but we're not playing this anymore so I can't 100% be sure/recreate it.

[crash-2024-10-06_11.17.22-client.txt](https://github.com/user-attachments/files/17974715/crash-2024-10-06_11.17.22-client.txt)

**Comment by screret** [comment]
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.m_129894_()" because the return value of "argent_matter.gcyr.common.entity.RocketEntity.m_20194_()" is null
	at argent_matter.gcyr.common.entity.RocketEntity.lambda$new$9(RocketEntity.java:170) ~[gcyr-1.20.1-0.2.4.jar%23302!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.misc.FluidStorage.onContentsChanged(FluidStorage.java:107) ~[ldlib-forge-1.20.1-1.0.28.a.jar%23406!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.misc.FluidStorage.setFluid(FluidStorage.java:52) ~[ldlib-forge-1.20.1-1.0.28.a.jar%23406!/:?] {re:classloading}
	at argent_matter.gcyr.common.entity.RocketEntity.m_7378_(RocketEntity.java:969) ~[gcyr-1.20.1-0.2.4.jar%23302!/:?] {re:classloading}
	at net.minecraft.world.entity.Entity.m_20258_(Entity.java:1750) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:ldlib-common.mixins.json:accessor.EntityAccessor,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:APP:carryon.mixins.json:EntityMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:kubejs-forge.mixins.json:EntityMixin,pl:mixin:APP:kubejs-common.mixins.json:EntityMixin,pl:mixin:APP:gtceu.mixins.json:EntityMixin,pl:mixin:APP:gcyr.mixins.json:EntityBorderMixin,pl:mixin:APP:gcyr.mixins.json:EntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.EntityType.m_185988_(EntityType.java:532) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType,pl:mixin:APP:flywheel.mixins.json:EntityTypeMixin,pl:mixin:A}
	at net.minecraft.Util.m_137521_(Util.java:419) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:UtilMixin,pl:mixin:APP:ftbchunks-common.mixins.json:UtilMixin,pl:mixin:APP:smoothboot.mixins.json:UtilMixin,pl:mixin:A}
	at net.minecraft.world.entity.EntityType.m_20642_(EntityType.java:529) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType,pl:mixin:APP:flywheel.mixins.json:EntityTypeMixin,pl:mixin:A}
	at tschipp.carryon.common.carry.CarryOnData.getEntity(CarryOnData.java:127) ~[carryon-forge-1.20.1-2.1.2.7.jar%23267!/:2.1.2.7] {re:mixin,re:computing_frames,re:classloading}
	at tschipp.carryon.client.render.CarryRenderHelper.getRenderEntity(CarryRenderHelper.java:294) ~[carryon-forge-1.20.1-2.1.2.7.jar%23267!/:2.1.2.7] {re:mixin,re:classloading}
	at tschipp.carryon.client.render.CarryRenderHelper.getRenderWidth(CarryRenderHelper.java:331) ~[carryon-forge-1.20.1-2.1.2.7.jar%23267!/:2.1.2.7] {re:mixin,re:classloading}
	at net.minecraft.client.model.HumanoidModel.handler$zha000$onSetupAnimations(HumanoidModel.java:542) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:carryon.mixins.json:HumanoidModelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
```
omfg. it's carryon loading the entity on the client and thus, erroring a loading thing I did thart requires the server.

**Comment by Pyriana** [comment]
> ```
> java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.m_129894_()" because the return value of "argent_matter.gcyr.common.entity.RocketEntity.m_20194_()" is null
> 	at argent_matter.gcyr.common.entity.RocketEntity.lambda$new$9(RocketEntity.java:170) ~[gcyr-1.20.1-0.2.4.jar%23302!/:?] {re:classloading}
> 	at com.lowdragmc.lowdraglib.misc.FluidStorage.onContentsChanged(FluidStorage.java:107) ~[ldlib-forge-1.20.1-1.0.28.a.jar%23406!/:?] {re:classloading}
> 	at com.lowdragmc.lowdraglib.misc.FluidStorage.setFluid(FluidStorage.java:52) ~[ldlib-forge-1.20.1-1.0.28.a.jar%23406!/:?] {re:classloading}
> 	at argent_matter.gcyr.common.entity.RocketEntity.m_7378_(RocketEntity.java:969) ~[gcyr-1.20.1-0.2.4.jar%23302!/:?] {re:classloading}
> 	at net.minecraft.world.entity.Entity.m_20258_(Entity.java:1750) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:ldlib-common.mixins.json:accessor.EntityAccessor,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:APP:carryon.mixins.json:EntityMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:kubejs-forge.mixins.json:EntityMixin,pl:mixin:APP:kubejs-common.mixins.json:EntityMixin,pl:mixin:APP:gtceu.mixins.json:EntityMixin,pl:mixin:APP:gcyr.mixins.json:EntityBorderMixin,pl:mixin:APP:gcyr.mixins.json:EntityMixin,pl:mixin:A}
> 	at net.minecraft.world.entity.EntityType.m_185988_(EntityType.java:532) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType,pl:mixin:APP:flywheel.mixins.json:EntityTypeMixin,pl:mixin:A}
> 	at net.minecraft.Util.m_137521_(Util.java:419) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:UtilMixin,pl:mixin:APP:ftbchunks-common.mixins.json:UtilMixin,pl:mixin:APP:smoothboot.mixins.json:UtilMixin,pl:mixin:A}
> 	at net.minecraft.world.entity.EntityType.m_20642_(EntityType.java:529) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType,pl:mixin:APP:flywheel.mixins.json:EntityTypeMixin,pl:mixin:A}
> 	at tschipp.carryon.common.carry.CarryOnData.getEntity(CarryOnData.java:127) ~[carryon-forge-1.20.1-2.1.2.7.jar%23267!/:2.1.2.7] {re:mixin,re:computing_frames,re:classloading}
> 	at tschipp.carryon.client.render.CarryRenderHelper.getRenderEntity(CarryRenderHelper.java:294) ~[carryon-forge-1.20.1-2.1.2.7.jar%23267!/:2.1.2.7] {re:mixin,re:classloading}
> 	at tschipp.carryon.client.render.CarryRenderHelper.getRenderWidth(CarryRenderHelper.java:331) ~[carryon-forge-1.20.1-2.1.2.7.jar%23267!/:2.1.2.7] {re:mixin,re:classloading}
> 	at net.minecraft.client.model.HumanoidModel.handler$zha000$onSetupAnimations(HumanoidModel.java:542) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:carryon.mixins.json:HumanoidModelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> ```
> 
> omfg. it's carryon loading the entity on the client and thus, erroring a loading thing I did thart requires the server.

I did notice that carryon can pick up the rocket heh. The landing is also slightly off like the rockets don't land on the launch pads exactly they land a few x/z coords off like 1-3, I can't figure out a pattern for it.

**Comment by screret** [comment]
yeah it should just be blacklisted from carryon, someone report back if that fixes this.

**Comment by screret** [comment]
will reopen if this happens with the fix
